### ISSUE TITLE
TradeShop Plugin Compatibility Issues

### ISSUE THREAD

**Issue by MildKid** [Kikisito/NFCNotes#14]
**Describe the bug**
I can't use notes with the TradeShop plugin.

**To Reproduce**
Steps to reproduce the behavior. Notes don't work with the tradeshop plugin: https://www.spigotmc.org/resources/tradeshop.32762/

**Expected behavior**
I expected to be able to use the notes as the cost or product. Tradeshop is typically pretty good at handling custom items.

**Additional context**
This might be on their end. I'm reporting it to them as well.

**Comment by Kikisito** [comment]
I'll check this as soon as I can. Are your notes issued with the issuer name? Please attach your config.yml

**Comment by MildKid** [comment]
I think I disabled that. 

I've attached the text of the config.yml file:
[config.txt](https://github.com/Kikisito/NFCNotes/files/11636536/config.txt)

**Comment by Kikisito** [comment]
I'm currently doing my final exams. As soon as I can I'll look into the issue. Your config file seems fine

**Comment by Kikisito** [comment]
It seems that the issue comes from TradeShop as it doesn't correctly compare the attributes of the stored note with the note that the player is trying to use. It thinks the notes are different. This issue should be fixed on TradeShop's end.

If you really need a shop that supports NFCNotes, I recommend [Shopkeepers](https://dev.bukkit.org/projects/shopkeepers).

I'm sorry for the delay and for not being able to do more. If you have any other issues, please tell me!

**Comment by Kikisito** [comment]
TradeShop should also look for [PersistentDataContainers](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/persistence/PersistentDataContainer.html), which is a type of data storage that NFCNotes will use in the future instead of attributes.
